import type { CaptionPreset } from "@/shared/schemas/caption-style";

export const DEFAULT_CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: "karaoke",
    name: "Karaoke",
    isDefault: true,
    isCustom: false,
    config: {
      id: "karaoke",
      name: "Karaoke",
      fontFamily: "Impact, Arial Black, sans-serif",
      fontWeight: 900,
      fontSize: 0.08,
      textColor: "#ffffff",
      backgroundType: "none",
      strokeColor: "#000000",
      strokeWidth: 4,
      textTransform: "uppercase",
      animation: "karaoke",
      wordHighlightColor: "#b7ff3c",
      wordHighlightAnimation: "fill",
      position: "bottom",
      letterSpacing: 2,
      lineHeight: 1.1,
      shadow: { color: "#000000", blur: 10, offsetX: 2, offsetY: 3 }
    }
  },
  {
    id: "deep-diver",
    name: "Deep Diver",
    isDefault: false,
    isCustom: false,
    config: {
      id: "deep-diver",
      name: "Deep Diver",
      fontFamily: "Inter, Arial, sans-serif",
      fontWeight: 800,
      fontSize: 0.058,
      textColor: "#101010",
      backgroundColor: "#f5f5f5",
      backgroundType: "pill",
      strokeWidth: 0,
      textTransform: "none",
      animation: "fade",
      position: "bottom",
      letterSpacing: 0,
      lineHeight: 1.35,
      borderRadius: 24,
      shadow: { color: "#000000", blur: 6, offsetX: 0, offsetY: 4 }
    }
  },
  {
    id: "pod-p",
    name: "Pod P",
    isDefault: false,
    isCustom: false,
    config: {
      id: "pod-p",
      name: "Pod P",
      fontFamily: "Arial Black, Arial, sans-serif",
      fontWeight: 900,
      fontSize: 0.066,
      textColor: "#ffffff",
      backgroundColor: "#151515",
      backgroundType: "rectangle",
      strokeColor: "#000000",
      strokeWidth: 2,
      textTransform: "uppercase",
      animation: "pop",
      wordHighlightColor: "#ffcc00",
      wordHighlightAnimation: "background",
      position: "bottom",
      letterSpacing: 1,
      lineHeight: 1.15,
      borderRadius: 8,
      shadow: { color: "#000000", blur: 10, offsetX: 0, offsetY: 5 }
    }
  },
  {
    id: "popline",
    name: "Popline",
    isDefault: false,
    isCustom: false,
    config: {
      id: "popline",
      name: "Popline",
      fontFamily: "Poppins, Inter, sans-serif",
      fontWeight: 900,
      fontSize: 0.072,
      textColor: "#ffffff",
      backgroundType: "none",
      strokeColor: "#121212",
      strokeWidth: 3,
      textTransform: "uppercase",
      animation: "bounce",
      wordHighlightColor: "#ff4bd8",
      wordHighlightAnimation: "scale",
      position: "bottom",
      letterSpacing: 1,
      lineHeight: 1.1,
      shadow: { color: "#30d5ff", blur: 0, offsetX: 3, offsetY: 4 }
    }
  },
  {
    id: "seamless-bounce",
    name: "Seamless Bounce",
    isDefault: false,
    isCustom: false,
    config: {
      id: "seamless-bounce",
      name: "Seamless Bounce",
      fontFamily: "Montserrat, Arial, sans-serif",
      fontWeight: 900,
      fontSize: 0.069,
      textColor: "#ffffff",
      backgroundType: "glow",
      strokeColor: "#1d1d1d",
      strokeWidth: 3,
      textTransform: "uppercase",
      animation: "bounce",
      wordHighlightColor: "#7cff6b",
      wordHighlightAnimation: "fill",
      position: "center",
      letterSpacing: 1,
      lineHeight: 1.05,
      shadow: { color: "#74ff6b", blur: 12, offsetX: 0, offsetY: 0 }
    }
  },
  {
    id: "beasty",
    name: "Beasty",
    isDefault: false,
    isCustom: false,
    config: {
      id: "beasty",
      name: "Beasty",
      fontFamily: "Anton, Impact, sans-serif",
      fontWeight: 900,
      fontSize: 0.085,
      textColor: "#ffef5a",
      backgroundType: "none",
      strokeColor: "#111111",
      strokeWidth: 5,
      textTransform: "uppercase",
      animation: "shake",
      wordHighlightColor: "#ffffff",
      wordHighlightAnimation: "scale",
      position: "bottom",
      letterSpacing: 1,
      lineHeight: 1,
      shadow: { color: "#ff3333", blur: 4, offsetX: 3, offsetY: 3 }
    }
  },
  {
    id: "youshaei",
    name: "Youshaei",
    isDefault: false,
    isCustom: false,
    config: {
      id: "youshaei",
      name: "Youshaei",
      fontFamily: "Arial Black, Arial, sans-serif",
      fontWeight: 900,
      fontSize: 0.063,
      textColor: "#ffffff",
      backgroundColor: "#0b0b0b",
      backgroundType: "pill",
      strokeColor: "#000000",
      strokeWidth: 1,
      textTransform: "uppercase",
      animation: "slide",
      wordHighlightColor: "#00e6ff",
      wordHighlightAnimation: "background",
      position: "top",
      letterSpacing: 1,
      lineHeight: 1.15,
      borderRadius: 20,
      shadow: { color: "#000000", blur: 8, offsetX: 0, offsetY: 4 }
    }
  },
  {
    id: "mozi",
    name: "Mozi",
    isDefault: false,
    isCustom: false,
    config: {
      id: "mozi",
      name: "Mozi",
      fontFamily: "Trebuchet MS, Arial, sans-serif",
      fontWeight: 800,
      fontSize: 0.062,
      textColor: "#161616",
      backgroundColor: "#e9f7ff",
      backgroundType: "pill",
      strokeWidth: 0,
      textTransform: "capitalize",
      animation: "pop",
      wordHighlightColor: "#0f8cff",
      wordHighlightAnimation: "fill",
      position: "bottom",
      letterSpacing: 0,
      lineHeight: 1.28,
      borderRadius: 18,
      shadow: { color: "#05111f", blur: 6, offsetX: 0, offsetY: 4 }
    }
  },
  {
    id: "glitch-infinite",
    name: "Glitch Infinite",
    isDefault: false,
    isCustom: false,
    config: {
      id: "glitch-infinite",
      name: "Glitch Infinite",
      fontFamily: "Courier New, monospace",
      fontWeight: 900,
      fontSize: 0.07,
      textColor: "#fbbf24",
      backgroundType: "none",
      strokeColor: "#ef4444",
      strokeWidth: 2,
      textTransform: "uppercase",
      animation: "glitch",
      wordHighlightColor: "#38f8ff",
      wordHighlightAnimation: "fill",
      position: "center",
      letterSpacing: 3,
      lineHeight: 1.1,
      shadow: { color: "#ef4444", blur: 2, offsetX: 2, offsetY: 0 }
    }
  },
  {
    id: "baby-earthquake",
    name: "Baby Earthquake",
    isDefault: false,
    isCustom: false,
    config: {
      id: "baby-earthquake",
      name: "Baby Earthquake",
      fontFamily: "Georgia, serif",
      fontWeight: 700,
      fontSize: 0.06,
      textColor: "#111111",
      backgroundColor: "#f5f5f5",
      backgroundType: "rectangle",
      strokeWidth: 0,
      textTransform: "lowercase",
      animation: "shake",
      wordHighlightColor: "#ff477e",
      wordHighlightAnimation: "background",
      position: "bottom",
      letterSpacing: 0,
      lineHeight: 1.25,
      borderRadius: 4,
      shadow: { color: "#000000", blur: 4, offsetX: 1, offsetY: 2 }
    }
  }
];
